## miniconf makefiles ## 1.1 ##

TOPDIR := ..

TEXT = make_profile xlogout

install :
	$Qinstall -d $(DESTDIR)$(LIBEXECDIR)
	$Qinstall $(TEXT) $(DESTDIR)$(LIBEXECDIR)

include $(TOPDIR)/.config/rules.mk
