## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

systray_src = egg-marshal.c \
    eggtraymanager.c \
    fixedtip.c \
    main.c
systray_cflags = $(GTK2_CFLAGS) 
systray_libs = $(GTK2_LIBS) 
systray_type = lib 

include $(TOPDIR)/.config/rules.mk
